package com.ar.edu.um.mtsanchez.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ProfessorAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProfessorAllPropertiesEquals(Professor expected, Professor actual) {
        assertProfessorAutoGeneratedPropertiesEquals(expected, actual);
        assertProfessorAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProfessorAllUpdatablePropertiesEquals(Professor expected, Professor actual) {
        assertProfessorUpdatableFieldsEquals(expected, actual);
        assertProfessorUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProfessorAutoGeneratedPropertiesEquals(Professor expected, Professor actual) {
        assertThat(actual)
            .as("Verify Professor auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProfessorUpdatableFieldsEquals(Professor expected, Professor actual) {
        assertThat(actual)
            .as("Verify Professor relevant properties")
            .satisfies(a -> assertThat(a.getFirstName()).as("check firstName").isEqualTo(expected.getFirstName()))
            .satisfies(a -> assertThat(a.getLastName()).as("check lastName").isEqualTo(expected.getLastName()))
            .satisfies(a -> assertThat(a.getEmail()).as("check email").isEqualTo(expected.getEmail()))
            .satisfies(a -> assertThat(a.getHireDate()).as("check hireDate").isEqualTo(expected.getHireDate()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProfessorUpdatableRelationshipsEquals(Professor expected, Professor actual) {
        // empty method
    }
}
